### ISSUE TITLE
Problem 5 We seem to be losing a lot of data points here.

### ISSUE THREAD

**Issue by iangow** [vickyyin1493/Replication-FFJR#10]
@vickyyin1493 @shizhe75 

> Problem 5 Evidence for supporting the claim made in FFJR on "large fraction of stock splits have been followed closely by dividend increases" We seem to be losing a lot of data points here. If we removed the filter for day_gap == 0, we would be able to get data. We were not sure if it's appropriate.

Where is `day_gap == 0` meant to be doing? In the solution guide, it's only used to reduce the data to split-level statistics. It's not used in creating any data frames.

**Comment by shizhe75** [comment]
Thank you @iangow. We have now removed this.
